### ISSUE TITLE
trouble installing cyREST

### ISSUE THREAD

**Issue by kaijagahm** [RonaldVisser/dendroNetwork#3]
Hi @RonaldVisser--I'm working on reviewing your package for rOpenSci, and I've run into trouble installing cyREST, which seems to be necessary in order to run the R connection to Cytoscape. I know this isn't a problem with your package per se, and if you don't know the solution I will try to ask for help from the cyREST folks. But I figured I'd ask if you've encountered this problem before.

I installed Java on my computer (Mac), and I downloaded cyREST from [here](https://apps.cytoscape.org/apps/cyrest). But when I tried to open the .jar file, I got the following error message, and I can't figure out where to go from here. 

<img width="254" alt="Screen Shot 2024-02-26 at 12 29 33" src="https://github.com/RonaldVisser/dendroNetwork/assets/37053323/4d950c4a-c0d0-4b6c-a4b7-c7379ba623e1">

The reason I tried installing cyREST in the first place was because when I tried to run `cyto_create_graph(g_hol)` following your README, I got the following error:

```
Oh no! I can't find Cytoscape. RCy3 can not continue!
Please check that Cytoscape is running, CyREST is installed and your base.url parameter is correct.
Error in value[[3L]](cond) : object 'res' not found
Error in cyrestGET("version", base.url = base.url) : 
  object 'res' not found
```
Does this look familiar to you at all? Any ideas on how to fix it?

**Comment by RonaldVisser** [comment]
Thanks for reviewing :)

That is weird. I have never installed cyREST as a separate instance. I always install Cytoscape and cyREST should be part of the installation of Cytoscape. What you could do is to install Cytoscape and than load RCy3 in R and try:
 `cytoscapePing()`

I don't have a Mac, so I can not try this myself. 

Let me know if this helps you!

**Comment by kaijagahm** [comment]
Thanks! I just tried doing that and still got the error. Posted it over on the RCy3 GitHub page, since that seems to be where the error lies. Fingers crossed. (https://github.com/cytoscape/RCy3/issues/219)

If I'm not able to get this working, I will just submit a review of the non-Cytoscape portions of your package.

**Comment by RonaldVisser** [comment]
I have tried to install Cytoscape under Arch Linux in a Virtualbox to see if I could reproduce your issue, but Cytoscape seems to crash after starting at the moment. I ran into unexpected bugs...  I did find this: https://cytoscape.org/common_issues.html

**Comment by kaijagahm** [comment]
I got it working, actually! Seems like it was a problem with my computer, not Cytoscape. Restarting the whole computer fixed things. Thank you for the help!

**Comment by RonaldVisser** [comment]
Glad to hear that you solved this!
